# Generated by Django 3.2.13 on 2022-05-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('main_img', models.ImageField(blank=True, default='images/dog.png', null=True, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Core',
            },
        ),
        migrations.CreateModel(
            name='CoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, null=True)),
                ('event_desc', models.CharField(max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core', to='core.core')),
            ],
            options={
                'verbose_name_plural': 'CoreHistory',
            },
        ),
    ]
