# Generated by Django 3.2.13 on 2022-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='chip_number',
            new_name='asset_number',
        ),
        migrations.RenameField(
            model_name='core',
            old_name='date_of_birth',
            new_name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='core',
            name='defining_marks',
        ),
        migrations.RemoveField(
            model_name='core',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='core',
            name='sex',
        ),
        migrations.AddField(
            model_name='corehistory',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='type',
            field=models.CharField(blank=True, choices=[('Vehicle', 'Vehicle'), ('Power Products', 'Power Products'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
