# Generated by Django 3.2.13 on 2022-05-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220530_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='impact',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100, null=True),
        ),
    ]
