# Generated by Django 3.2.13 on 2022-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220506_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='contact_number1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
