# Generated by Django 3.2.13 on 2022-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_corehistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='corehistory',
            name='km_or_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
